<?php
namespace app\modules\dbma\controllers;
 


class EmployeeController extends \app\components\XQEdit\XQEditController
{ 
    protected $MAIN_MODEL 	    =   'app\models\Employee';     
    public function init()  
    {
        parent::init();
        
         
        $this->VIEWPARA['XQEDIT']['index_columns'] = [  
            'EmployeeCode',
            'TitleThai',
            'FirstName_Thai',
            'LastName_Thai',
            'TitleEng',
            'FirstName_Eng',
            'LastName_Eng',
            //'EmployeeStatus',
            //'Birthday',
            //'Age',
            //'Sex',
            //'Origin',
            //'Nation',
            //'Religion',
            //'CommandeerStatus',
            //'Height',
            //'Weight',
            //'CompanyCode',
            'DivisionCode',
            'DeptCode',
            //'SectionCode',
            //'EmployeePosition',
            //'DateToStart',
            //'DateToEnd',
            //'Resign',
            //'DateToTest',
            //'Salary',
            //'DayIncome',
            //'Address:ntext',
            //'Province',
            //'ZipCode',
            //'Telephone',
            //'Address_Now:ntext',
            //'Province_Now',
            //'ZipCode_Now',
            //'Telephone_Now',
            //'MarryStatus',
            //'CoupleName',
            //'CoupleWorkAddress:ntext',
            //'CoupleWorkProvince',
            //'CoupleWorkZipCode',
            //'CoupleWorkTelephone',
            //'ManyChild',
            //'FatherName',
            //'FatherAge',
            //'MatherName',
            //'MatherAge',
            //'ManyRelation',
            //'ManyBrother',
            //'ManySister',
            //'ManyYoungerBrother',
            //'ManyYoungerSister',
            //'LineRelation',
            //'Qualification',
            //'Field',
            //'Institue',
            //'GPA',
            //'OldCompany',
            //'OldPosition',
            //'OldDatetoStart',
            //'OldDatetoEnd',
            //'OldDay',
            //'OldMonth',
            //'OldYear',
            //'IDCode',
            //'IDAmphur',
            //'IDProvince',
            //'IDDatetoEnd',
            //'TaxCode',
            //'SocialCode',
            //'AccountNo',
            //'Bank',
            //'Branch',
            //'Photo',
            //'UseTimeAttendance:datetime',
            //'SubSectionCode',
            //'ShoeNo',
            //'ShoeColor',
            //'MapPhoto',
            //'EarnType',
            //'EmployeeJobFunction',
            //'BranchCode',
            //'EmployeeCodeExternal',
            //'BloodGroup',
            //'UserName',
            //'LastUpdate',
            //'FatherLife',
            //'MotherLife',
            //'AfterTestDesc',
             
        ];
    }      
}


