<?php

namespace app\models;

use \app\components\XLib;

/**
 * This is the model class for table "x_booking".
 *
 * @property string $doc_no
 * @property string $doc_date
 * @property int $track_id
 * @property string $title
 * @property string $dt_start
 * @property string $dt_end
 * @property string $remark
 * @property string $username
 * @property string $status
 */
class XBooking extends \yii\db\ActiveRecord
{
    public static  $track_LIST  = [
        1 => [
            'id' => '1',
            'track_name' => 'ห้องประชุม ชั้น 2',
            'track_color' => '#6699ff',            
        ],
        2 => [
            'id' => '2',
            'track_name' => 'ห้องรับแขก 1 ชั้น 1',
            'track_color' => '#bf80ff',            
        ],
        // 3 => [
        //     'id' => '3',
        //     'track_name' => 'ห้องรับแขก 2 ชั้น 1',
        //     'track_color' => '#ff80bf',            
        // ],
    ];
    public function afterFind()
    {
        parent::afterFind();
        $this->doc_date             = XLib::dateConv($this->doc_date, 'a');


        $this->dt_start             = XLib::dateTimeConv($this->dt_start, 'a');
        $this->dt_end               = XLib::dateTimeConv($this->dt_end, 'a');

    }
    public function beforeSave($insert)
    {
        parent::beforeSave($insert);
        $this->doc_date = XLib::dateConv($this->doc_date, 'b');
        $this->dt_start = XLib::dateTimeConv($this->dt_start, 'b');
        $this->dt_end = XLib::dateTimeConv($this->dt_end, 'b');
        return true;
    }

    //public $dt_range;
    // public function beforeSave($insert)
    // {
    //     parent::beforeSave($insert);
    //     $this->username = Yii::$app->user->identity->username;
    //     return true;
    // }
    // public function getDt_range(){

    //     if(!empty($this->dt_start)){
    //         //$getDate = new DateTime();
    //         //$getDate->setTimestamp($attribute);
    //         //$date = $getDate->format('Y-m-d H:i:s');

    //         return   date("d/m/Y H:i", strtotime($this->dt_start)) . ' - ' .
    //             date("d/m/Y H:i", strtotime($this->dt_end));           

    //     } else {
    //         return 'xx';
    //     }

    // }
    // public function afterFind()
    // {
    //     $name = 'dt_start1';
    //     $attribute = $this->getAttribute($name);
    //     if(!empty($attribute)){
    //         //$getDate = new DateTime();
    //         //$getDate->setTimestamp($attribute);
    //         //$date = $getDate->format('Y-m-d H:i:s');

    //         // $str =  date("dd-mm-yyyy HH:mm", strtotime($this->dt_start)) . ' - ' .
    //         //     date("d/m/Y H:i", strtotime($this->dt_end));
    //         $str =  date("dd-mm-yyyy HH:mm", strtotime($this->dt_start));

    //         $this->setAttribute($name, $str);

    //     }

    //     parent::afterFind(); // TODO: Change the autogenerated stub
    // }    

    public function genDocNumber()
    {


        $prefix = 'BKK'
            . substr('0' . (date('y') + 0), -2)
            . substr('0' . (date('m') + 0), -2);
        $lastdoc = $this->find()
            ->select('max(doc_no) as doc_no')
            ->where(['left(doc_no,7)' => $prefix])
            ->one();
        $next_num = ($lastdoc) ? (substr($lastdoc->doc_no, 7, 3) + 1) : 1;

        return $prefix . substr('000' . $next_num, -3);
    }


    // ************************************************************************************************    
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'x_booking';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['doc_no'], 'required'],
            [['doc_no', 'title', 'remark', 'username', 'status'], 'string'],
            [['doc_date', 'dt_start', 'dt_end'], 'safe'],
            [['track_id'], 'integer'],
            [['doc_no'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'doc_no' => 'เลขที่',
            'doc_date' => 'วันที่ทำรายการ',
            'track_id' => 'Track ID',
            'title' => 'การใช้งาน',
            'dt_start' => 'วันที่จอง',
            'dt_end' => 'จองถึง',
            'remark' => 'หมายเหตุ',
            'username' => 'ผู้จอง',
            'status' => 'Status',
        ];
    }
}
